version: "3"
services:
  messaging:
    build: .
    ports:
      - 8086:8086
    environment:
      KUMULUZEE_CONFIG_ETCD_HOSTS: http://etcd:2379
      KUMULUZEE_DISCOVERY_ETCD_HOSTS: http://etcd:2379
      KUMULUZEE_SERVER_BASEURL: http://messaging:8086
    depends_on:
      - etcd
      - users

  etcd:
      image: elcolio/etcd:2.0.10
      ports:
        - 2379:2379
        - 2380:2380
        - 4001:4001
        - 7001:7001
  etcd-browser:
    image: buddho/etcd-browser
    ports:
      - 8000:8000
    environment:
      ETCD_HOST: http://etcd
      AUTH_PASS: doe
    depends_on:
      - etcd

  users:
    image: tomisebjanic/rso-users:0.10
    ports:
      - 8082:8082
    environment:
      KUMULUZEE_DATASOURCES0_CONNECTIONURL: jdbc:postgresql://postgres:5432/rsouser
      KUMULUZEE_CONFIG_ETCD_HOSTS: http://etcd:2379
      KUMULUZEE_DISCOVERY_ETCD_HOSTS: http://etcd:2379
      KUMULUZEE_SERVER_BASEURL: http://users:8082
    depends_on:
      - postgres
      - etcd

  postgres:
    image: postgres:10.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rsouser

  auth:
    image: tomisebjanic/rso-auth:1.0.2
    ports:
      - 8089:8089
    environment:
      KUMULUZEE_CONFIG_ETCD_HOSTS: http://etcd:2379
      KUMULUZEE_DISCOVERY_ETCD_HOSTS: http://etcd:2379
      KUMULUZEE_SERVER_BASEURL: http://auth:8089
    depends_on:
      - etcd